### ISSUE TITLE
This plugin won't install on my iPhone under iOS version 17.1.1

### ISSUE THREAD

**Issue by oldfartdeveloper** [macstories/obsidian-shortcut-launcher#11]
When I attempt to `Install` **Shortcut Launcher**, I get a temporary dialog `Failed to install plugins "Shortcut Launcher`.

### Diagnostic message:

| 2023-11-24T18:47:08.807Z | @capacitor://localhost/app.js:1:237031 | error | `{"status":404,"headers":{"x-content-type-options":"nosniff","Date":"Fri, 24 Nov 2023 18:46:52 GMT","Content-Encoding":"gzip","x-xss-protection":"0","x-frame-options":"deny","x-github-request-id":"6F9B:2379:18AA1AC:1A2E659:6560EF9C","Server":"GitHub.com","referrer-policy":"no-referrer-when-downgrade","Cache-Control":"no-cache","Content-Type":"text/plain; charset=utf-8","Vary":"X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With","content-security-policy":"default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'","Strict-Transport-Security":"max-age=31536000; includeSubdomains; preload","Content-Length":"29"}}` |

I can see that `@capacitor` above should be assigned to `https`; this is why it's getting a **404**.  Smells like a configuration problem.  Hope this helps.

**Comment by davebhc71** [comment]
Same here with iPadOS17.2 Beta2…won’t install!

**Comment by Finnvoor** [comment]
Hi, this appears to be a bug with the way Obsidian checks for updates.  There is no new update available, so there is nothing to install and it fails.  It shouldn't be happening anymore if you close and reopen the app.

**Comment by oldfartdeveloper** [comment]
Yup, restarting Obsidian worked, thanks!
