### ISSUE TITLE
Separator resets when editing launcher

### ISSUE THREAD

**Issue by colintedford** [macstories/obsidian-shortcut-launcher#4]
When I open a launcher to edit it on iOS, my custom separator gets reset to a comma.

I think it only affects what is shown in the settings. The shortcut still behaves as if the separator is correct.

**Comment by Finnvoor** [comment]
fixed and included in [release 1.0.1](https://github.com/macstories/obsidian-shortcut-launcher/releases/tag/1.0.1)
